version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: ejes_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Usa variables de entorno
      MYSQL_DATABASE: ejes_db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "3306:3306" # Mapea el puerto si necesitas conectarte desde tu host
    volumes:
      - ./mysql_data:/var/lib/mysql # Volumen para persistencia de datos
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Script de inicialización
    networks:
      - tts-network

  backend:
    image: backend
    container_name: backend-container
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql_db
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ejes_db
    depends_on:
      mysql_db:      
        condition: service_healthy # Espera a que MySQL esté listo antes de iniciar el backend y no tener errores de race condition
    volumes:
      - ./shared:/app/shared-files
    networks:
      - tts-network

  api_proxy:
    image: api_proxy
    container_name: api_proxy-container
    ports:
      - "5001:5000" # puerto host:puerto contenedor
    # volumes:
    #   - ./shared:/app/shared-files
    volumes:
      - ./shared:/app/shared-files
      - ./secrets:/app/secrets:ro  # :ro = solo lectura
    environment:
      # Variable apunta al archivo MONTADO via volumen
      - GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/gcloud_credentials.json
    networks:
      - tts-network      
    depends_on:
      - backend

volumes:
  mysql_data:

networks:
  tts-network:
    driver: bridge